/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// ApiAtlasDiskBackupReplicaSetView Details of the replica set snapshot that MongoDB Cloud created.
type ApiAtlasDiskBackupReplicaSetView struct {
	// Human-readable label that identifies the cloud provider that stores this snapshot. The resource returns this parameter when `\"type\": \"replicaSet\".`
	CloudProvider *string `json:"cloudProvider,omitempty"`
	// List that identifies the regions to which MongoDB Cloud copies the snapshot.
	CopyRegions []string `json:"copyRegions,omitempty"`
	// Date and time when MongoDB Cloud took the snapshot. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Human-readable phrase or sentence that explains the purpose of the snapshot. The resource returns this parameter when `\"status\": \"onDemand\"`.
	Description *string `json:"description,omitempty"`
	// Date and time when MongoDB Cloud deletes the snapshot. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// Human-readable label that identifies how often this snapshot triggers.
	FrequencyType *string `json:"frequencyType,omitempty"`
	// Unique 24-hexadecimal digit string that identifies the snapshot.
	Id *string `json:"id,omitempty"`
	// List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
	Links []Link `json:"links"`
	// Unique string that identifies the Amazon Web Services (AWS) Key Management Service (KMS) Customer Master Key (CMK) used to encrypt the snapshot. The resource returns this value when `\"encryptionEnabled\" : true`.
	MasterKeyUUID *string `json:"masterKeyUUID,omitempty"`
	// Version of the MongoDB host that this snapshot backs up.
	MongodVersion *string `json:"mongodVersion,omitempty"`
	// List that contains unique identifiers for the policy items.
	PolicyItems []string `json:"policyItems,omitempty"`
	// Human-readable label that identifies the replica set from which MongoDB Cloud took this snapshot. The resource returns this parameter when `\"type\": \"replicaSet\"`
	ReplicaSetName *string `json:"replicaSetName,omitempty"`
	// Human-readable label that identifies when this snapshot triggers.
	SnapshotType *string `json:"snapshotType,omitempty"`
	// Human-readable label that indicates the stage of the backup process for this snapshot.
	Status *string `json:"status,omitempty"`
	// Number of bytes taken to store the backup snapshot.
	StorageSizeBytes *int64 `json:"storageSizeBytes,omitempty"`
	// Human-readable label that categorizes the cluster as a replica set or sharded cluster.
	Type *string `json:"type,omitempty"`
}

// NewApiAtlasDiskBackupReplicaSetView instantiates a new ApiAtlasDiskBackupReplicaSetView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasDiskBackupReplicaSetView(links []Link) *ApiAtlasDiskBackupReplicaSetView {
	this := ApiAtlasDiskBackupReplicaSetView{}
	this.Links = links
	return &this
}

// NewApiAtlasDiskBackupReplicaSetViewWithDefaults instantiates a new ApiAtlasDiskBackupReplicaSetView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasDiskBackupReplicaSetViewWithDefaults() *ApiAtlasDiskBackupReplicaSetView {
	this := ApiAtlasDiskBackupReplicaSetView{}
	return &this
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetCloudProvider() string {
	if o == nil || isNil(o.CloudProvider) {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetCloudProviderOk() (*string, bool) {
	if o == nil || isNil(o.CloudProvider) {
    return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasCloudProvider() bool {
	if o != nil && !isNil(o.CloudProvider) {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetCopyRegions returns the CopyRegions field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetCopyRegions() []string {
	if o == nil || isNil(o.CopyRegions) {
		var ret []string
		return ret
	}
	return o.CopyRegions
}

// GetCopyRegionsOk returns a tuple with the CopyRegions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetCopyRegionsOk() ([]string, bool) {
	if o == nil || isNil(o.CopyRegions) {
    return nil, false
	}
	return o.CopyRegions, true
}

// HasCopyRegions returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasCopyRegions() bool {
	if o != nil && !isNil(o.CopyRegions) {
		return true
	}

	return false
}

// SetCopyRegions gets a reference to the given []string and assigns it to the CopyRegions field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetCopyRegions(v []string) {
	o.CopyRegions = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetCreatedAt() time.Time {
	if o == nil || isNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.CreatedAt) {
    return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasCreatedAt() bool {
	if o != nil && !isNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetDescription(v string) {
	o.Description = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetExpiresAt() time.Time {
	if o == nil || isNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.ExpiresAt) {
    return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasExpiresAt() bool {
	if o != nil && !isNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetFrequencyType returns the FrequencyType field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetFrequencyType() string {
	if o == nil || isNil(o.FrequencyType) {
		var ret string
		return ret
	}
	return *o.FrequencyType
}

// GetFrequencyTypeOk returns a tuple with the FrequencyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetFrequencyTypeOk() (*string, bool) {
	if o == nil || isNil(o.FrequencyType) {
    return nil, false
	}
	return o.FrequencyType, true
}

// HasFrequencyType returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasFrequencyType() bool {
	if o != nil && !isNil(o.FrequencyType) {
		return true
	}

	return false
}

// SetFrequencyType gets a reference to the given string and assigns it to the FrequencyType field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetFrequencyType(v string) {
	o.FrequencyType = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetId(v string) {
	o.Id = &v
}

// GetLinks returns the Links field value
func (o *ApiAtlasDiskBackupReplicaSetView) GetLinks() []Link {
	if o == nil {
		var ret []Link
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetLinksOk() ([]Link, bool) {
	if o == nil {
    return nil, false
	}
	return o.Links, true
}

// SetLinks sets field value
func (o *ApiAtlasDiskBackupReplicaSetView) SetLinks(v []Link) {
	o.Links = v
}

// GetMasterKeyUUID returns the MasterKeyUUID field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetMasterKeyUUID() string {
	if o == nil || isNil(o.MasterKeyUUID) {
		var ret string
		return ret
	}
	return *o.MasterKeyUUID
}

// GetMasterKeyUUIDOk returns a tuple with the MasterKeyUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetMasterKeyUUIDOk() (*string, bool) {
	if o == nil || isNil(o.MasterKeyUUID) {
    return nil, false
	}
	return o.MasterKeyUUID, true
}

// HasMasterKeyUUID returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasMasterKeyUUID() bool {
	if o != nil && !isNil(o.MasterKeyUUID) {
		return true
	}

	return false
}

// SetMasterKeyUUID gets a reference to the given string and assigns it to the MasterKeyUUID field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetMasterKeyUUID(v string) {
	o.MasterKeyUUID = &v
}

// GetMongodVersion returns the MongodVersion field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetMongodVersion() string {
	if o == nil || isNil(o.MongodVersion) {
		var ret string
		return ret
	}
	return *o.MongodVersion
}

// GetMongodVersionOk returns a tuple with the MongodVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetMongodVersionOk() (*string, bool) {
	if o == nil || isNil(o.MongodVersion) {
    return nil, false
	}
	return o.MongodVersion, true
}

// HasMongodVersion returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasMongodVersion() bool {
	if o != nil && !isNil(o.MongodVersion) {
		return true
	}

	return false
}

// SetMongodVersion gets a reference to the given string and assigns it to the MongodVersion field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetMongodVersion(v string) {
	o.MongodVersion = &v
}

// GetPolicyItems returns the PolicyItems field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetPolicyItems() []string {
	if o == nil || isNil(o.PolicyItems) {
		var ret []string
		return ret
	}
	return o.PolicyItems
}

// GetPolicyItemsOk returns a tuple with the PolicyItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetPolicyItemsOk() ([]string, bool) {
	if o == nil || isNil(o.PolicyItems) {
    return nil, false
	}
	return o.PolicyItems, true
}

// HasPolicyItems returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasPolicyItems() bool {
	if o != nil && !isNil(o.PolicyItems) {
		return true
	}

	return false
}

// SetPolicyItems gets a reference to the given []string and assigns it to the PolicyItems field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetPolicyItems(v []string) {
	o.PolicyItems = v
}

// GetReplicaSetName returns the ReplicaSetName field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetReplicaSetName() string {
	if o == nil || isNil(o.ReplicaSetName) {
		var ret string
		return ret
	}
	return *o.ReplicaSetName
}

// GetReplicaSetNameOk returns a tuple with the ReplicaSetName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetReplicaSetNameOk() (*string, bool) {
	if o == nil || isNil(o.ReplicaSetName) {
    return nil, false
	}
	return o.ReplicaSetName, true
}

// HasReplicaSetName returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasReplicaSetName() bool {
	if o != nil && !isNil(o.ReplicaSetName) {
		return true
	}

	return false
}

// SetReplicaSetName gets a reference to the given string and assigns it to the ReplicaSetName field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetReplicaSetName(v string) {
	o.ReplicaSetName = &v
}

// GetSnapshotType returns the SnapshotType field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetSnapshotType() string {
	if o == nil || isNil(o.SnapshotType) {
		var ret string
		return ret
	}
	return *o.SnapshotType
}

// GetSnapshotTypeOk returns a tuple with the SnapshotType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetSnapshotTypeOk() (*string, bool) {
	if o == nil || isNil(o.SnapshotType) {
    return nil, false
	}
	return o.SnapshotType, true
}

// HasSnapshotType returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasSnapshotType() bool {
	if o != nil && !isNil(o.SnapshotType) {
		return true
	}

	return false
}

// SetSnapshotType gets a reference to the given string and assigns it to the SnapshotType field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetSnapshotType(v string) {
	o.SnapshotType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetStatus() string {
	if o == nil || isNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetStatusOk() (*string, bool) {
	if o == nil || isNil(o.Status) {
    return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetStatus(v string) {
	o.Status = &v
}

// GetStorageSizeBytes returns the StorageSizeBytes field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetStorageSizeBytes() int64 {
	if o == nil || isNil(o.StorageSizeBytes) {
		var ret int64
		return ret
	}
	return *o.StorageSizeBytes
}

// GetStorageSizeBytesOk returns a tuple with the StorageSizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetStorageSizeBytesOk() (*int64, bool) {
	if o == nil || isNil(o.StorageSizeBytes) {
    return nil, false
	}
	return o.StorageSizeBytes, true
}

// HasStorageSizeBytes returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasStorageSizeBytes() bool {
	if o != nil && !isNil(o.StorageSizeBytes) {
		return true
	}

	return false
}

// SetStorageSizeBytes gets a reference to the given int64 and assigns it to the StorageSizeBytes field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetStorageSizeBytes(v int64) {
	o.StorageSizeBytes = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiAtlasDiskBackupReplicaSetView) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
    return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiAtlasDiskBackupReplicaSetView) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiAtlasDiskBackupReplicaSetView) SetType(v string) {
	o.Type = &v
}

func (o ApiAtlasDiskBackupReplicaSetView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CloudProvider) {
		toSerialize["cloudProvider"] = o.CloudProvider
	}
	if !isNil(o.CopyRegions) {
		toSerialize["copyRegions"] = o.CopyRegions
	}
	if !isNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !isNil(o.FrequencyType) {
		toSerialize["frequencyType"] = o.FrequencyType
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["links"] = o.Links
	}
	if !isNil(o.MasterKeyUUID) {
		toSerialize["masterKeyUUID"] = o.MasterKeyUUID
	}
	if !isNil(o.MongodVersion) {
		toSerialize["mongodVersion"] = o.MongodVersion
	}
	if !isNil(o.PolicyItems) {
		toSerialize["policyItems"] = o.PolicyItems
	}
	if !isNil(o.ReplicaSetName) {
		toSerialize["replicaSetName"] = o.ReplicaSetName
	}
	if !isNil(o.SnapshotType) {
		toSerialize["snapshotType"] = o.SnapshotType
	}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !isNil(o.StorageSizeBytes) {
		toSerialize["storageSizeBytes"] = o.StorageSizeBytes
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasDiskBackupReplicaSetView struct {
	value *ApiAtlasDiskBackupReplicaSetView
	isSet bool
}

func (v NullableApiAtlasDiskBackupReplicaSetView) Get() *ApiAtlasDiskBackupReplicaSetView {
	return v.value
}

func (v *NullableApiAtlasDiskBackupReplicaSetView) Set(val *ApiAtlasDiskBackupReplicaSetView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasDiskBackupReplicaSetView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasDiskBackupReplicaSetView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasDiskBackupReplicaSetView(val *ApiAtlasDiskBackupReplicaSetView) *NullableApiAtlasDiskBackupReplicaSetView {
	return &NullableApiAtlasDiskBackupReplicaSetView{value: val, isSet: true}
}

func (v NullableApiAtlasDiskBackupReplicaSetView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasDiskBackupReplicaSetView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


