/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiAtlasServerlessClusterDescriptionPatchView Settings that can be updated when a serverless cluster update is requested.
type ApiAtlasServerlessClusterDescriptionPatchView struct {
	// Flag that indicates whether termination protection is enabled on the cluster. If set to `true`, MongoDB Cloud won't delete the cluster. If set to `false`, MongoDB Cloud will delete the cluster.
	TerminationProtectionEnabled *bool `json:"terminationProtectionEnabled,omitempty"`
}

// NewApiAtlasServerlessClusterDescriptionPatchView instantiates a new ApiAtlasServerlessClusterDescriptionPatchView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasServerlessClusterDescriptionPatchView() *ApiAtlasServerlessClusterDescriptionPatchView {
	this := ApiAtlasServerlessClusterDescriptionPatchView{}
	var terminationProtectionEnabled bool = false
	this.TerminationProtectionEnabled = &terminationProtectionEnabled
	return &this
}

// NewApiAtlasServerlessClusterDescriptionPatchViewWithDefaults instantiates a new ApiAtlasServerlessClusterDescriptionPatchView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasServerlessClusterDescriptionPatchViewWithDefaults() *ApiAtlasServerlessClusterDescriptionPatchView {
	this := ApiAtlasServerlessClusterDescriptionPatchView{}
	var terminationProtectionEnabled bool = false
	this.TerminationProtectionEnabled = &terminationProtectionEnabled
	return &this
}

// GetTerminationProtectionEnabled returns the TerminationProtectionEnabled field value if set, zero value otherwise.
func (o *ApiAtlasServerlessClusterDescriptionPatchView) GetTerminationProtectionEnabled() bool {
	if o == nil || isNil(o.TerminationProtectionEnabled) {
		var ret bool
		return ret
	}
	return *o.TerminationProtectionEnabled
}

// GetTerminationProtectionEnabledOk returns a tuple with the TerminationProtectionEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasServerlessClusterDescriptionPatchView) GetTerminationProtectionEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.TerminationProtectionEnabled) {
    return nil, false
	}
	return o.TerminationProtectionEnabled, true
}

// HasTerminationProtectionEnabled returns a boolean if a field has been set.
func (o *ApiAtlasServerlessClusterDescriptionPatchView) HasTerminationProtectionEnabled() bool {
	if o != nil && !isNil(o.TerminationProtectionEnabled) {
		return true
	}

	return false
}

// SetTerminationProtectionEnabled gets a reference to the given bool and assigns it to the TerminationProtectionEnabled field.
func (o *ApiAtlasServerlessClusterDescriptionPatchView) SetTerminationProtectionEnabled(v bool) {
	o.TerminationProtectionEnabled = &v
}

func (o ApiAtlasServerlessClusterDescriptionPatchView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TerminationProtectionEnabled) {
		toSerialize["terminationProtectionEnabled"] = o.TerminationProtectionEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasServerlessClusterDescriptionPatchView struct {
	value *ApiAtlasServerlessClusterDescriptionPatchView
	isSet bool
}

func (v NullableApiAtlasServerlessClusterDescriptionPatchView) Get() *ApiAtlasServerlessClusterDescriptionPatchView {
	return v.value
}

func (v *NullableApiAtlasServerlessClusterDescriptionPatchView) Set(val *ApiAtlasServerlessClusterDescriptionPatchView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasServerlessClusterDescriptionPatchView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasServerlessClusterDescriptionPatchView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasServerlessClusterDescriptionPatchView(val *ApiAtlasServerlessClusterDescriptionPatchView) *NullableApiAtlasServerlessClusterDescriptionPatchView {
	return &NullableApiAtlasServerlessClusterDescriptionPatchView{value: val, isSet: true}
}

func (v NullableApiAtlasServerlessClusterDescriptionPatchView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasServerlessClusterDescriptionPatchView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


