/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiAtlasGCPPeerVpcRequestView struct for ApiAtlasGCPPeerVpcRequestView
type ApiAtlasGCPPeerVpcRequestView struct {
	// Unique 24-hexadecimal digit string that identifies the MongoDB Cloud network container that contains the specified network peering connection.
	ContainerId string `json:"containerId"`
	// Cloud service provider that determines the needed settings to configure the network connection for a virtual private connection.
	ProviderName string `json:"providerName"`
	// Details of the error returned when requesting a GCP network peering resource. The resource returns `null` if the request succeeded.
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// Human-readable label that identifies the GCP project that contains the network that you want to peer with the MongoDB Cloud VPC.
	GcpProjectId string `json:"gcpProjectId"`
	// Unique 24-hexadecimal digit string that identifies the network peering connection.
	Id *string `json:"id,omitempty"`
	// Human-readable label that identifies the network to peer with the MongoDB Cloud VPC.
	NetworkName string `json:"networkName"`
	// State of the network peering connection at the time you made the request.
	Status *string `json:"status,omitempty"`
}

// NewApiAtlasGCPPeerVpcRequestView instantiates a new ApiAtlasGCPPeerVpcRequestView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasGCPPeerVpcRequestView(containerId string, providerName string, gcpProjectId string, networkName string) *ApiAtlasGCPPeerVpcRequestView {
	this := ApiAtlasGCPPeerVpcRequestView{}
	this.ContainerId = containerId
	this.ProviderName = providerName
	this.GcpProjectId = gcpProjectId
	this.NetworkName = networkName
	return &this
}

// NewApiAtlasGCPPeerVpcRequestViewWithDefaults instantiates a new ApiAtlasGCPPeerVpcRequestView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasGCPPeerVpcRequestViewWithDefaults() *ApiAtlasGCPPeerVpcRequestView {
	this := ApiAtlasGCPPeerVpcRequestView{}
	return &this
}

// GetContainerId returns the ContainerId field value
func (o *ApiAtlasGCPPeerVpcRequestView) GetContainerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerId
}

// GetContainerIdOk returns a tuple with the ContainerId field value
// and a boolean to check if the value has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) GetContainerIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ContainerId, true
}

// SetContainerId sets field value
func (o *ApiAtlasGCPPeerVpcRequestView) SetContainerId(v string) {
	o.ContainerId = v
}

// GetProviderName returns the ProviderName field value
func (o *ApiAtlasGCPPeerVpcRequestView) GetProviderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderName
}

// GetProviderNameOk returns a tuple with the ProviderName field value
// and a boolean to check if the value has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) GetProviderNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ProviderName, true
}

// SetProviderName sets field value
func (o *ApiAtlasGCPPeerVpcRequestView) SetProviderName(v string) {
	o.ProviderName = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ApiAtlasGCPPeerVpcRequestView) GetErrorMessage() string {
	if o == nil || isNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) GetErrorMessageOk() (*string, bool) {
	if o == nil || isNil(o.ErrorMessage) {
    return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) HasErrorMessage() bool {
	if o != nil && !isNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *ApiAtlasGCPPeerVpcRequestView) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetGcpProjectId returns the GcpProjectId field value
func (o *ApiAtlasGCPPeerVpcRequestView) GetGcpProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GcpProjectId
}

// GetGcpProjectIdOk returns a tuple with the GcpProjectId field value
// and a boolean to check if the value has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) GetGcpProjectIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.GcpProjectId, true
}

// SetGcpProjectId sets field value
func (o *ApiAtlasGCPPeerVpcRequestView) SetGcpProjectId(v string) {
	o.GcpProjectId = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiAtlasGCPPeerVpcRequestView) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiAtlasGCPPeerVpcRequestView) SetId(v string) {
	o.Id = &v
}

// GetNetworkName returns the NetworkName field value
func (o *ApiAtlasGCPPeerVpcRequestView) GetNetworkName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetworkName
}

// GetNetworkNameOk returns a tuple with the NetworkName field value
// and a boolean to check if the value has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) GetNetworkNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.NetworkName, true
}

// SetNetworkName sets field value
func (o *ApiAtlasGCPPeerVpcRequestView) SetNetworkName(v string) {
	o.NetworkName = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ApiAtlasGCPPeerVpcRequestView) GetStatus() string {
	if o == nil || isNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) GetStatusOk() (*string, bool) {
	if o == nil || isNil(o.Status) {
    return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ApiAtlasGCPPeerVpcRequestView) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ApiAtlasGCPPeerVpcRequestView) SetStatus(v string) {
	o.Status = &v
}

func (o ApiAtlasGCPPeerVpcRequestView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["containerId"] = o.ContainerId
	}
	if true {
		toSerialize["providerName"] = o.ProviderName
	}
	if !isNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if true {
		toSerialize["gcpProjectId"] = o.GcpProjectId
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["networkName"] = o.NetworkName
	}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasGCPPeerVpcRequestView struct {
	value *ApiAtlasGCPPeerVpcRequestView
	isSet bool
}

func (v NullableApiAtlasGCPPeerVpcRequestView) Get() *ApiAtlasGCPPeerVpcRequestView {
	return v.value
}

func (v *NullableApiAtlasGCPPeerVpcRequestView) Set(val *ApiAtlasGCPPeerVpcRequestView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasGCPPeerVpcRequestView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasGCPPeerVpcRequestView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasGCPPeerVpcRequestView(val *ApiAtlasGCPPeerVpcRequestView) *NullableApiAtlasGCPPeerVpcRequestView {
	return &NullableApiAtlasGCPPeerVpcRequestView{value: val, isSet: true}
}

func (v NullableApiAtlasGCPPeerVpcRequestView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasGCPPeerVpcRequestView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


