/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiAtlasAzureProviderSettingsViewManualAllOf struct for ApiAtlasAzureProviderSettingsViewManualAllOf
type ApiAtlasAzureProviderSettingsViewManualAllOf struct {
	AutoScaling *ApiAtlasAzureProviderSettingsViewManualAllOfAutoScaling `json:"autoScaling,omitempty"`
	// Disk type that corresponds to the host's root volume for Azure instances. If omitted, the default disk type for the selected **providerSettings.instanceSizeName** applies.
	DiskTypeName *string `json:"diskTypeName,omitempty"`
	// Cluster tier, with a default storage and memory capacity, that applies to all the data-bearing hosts in your cluster.
	InstanceSizeName *string `json:"instanceSizeName,omitempty"`
	// Human-readable label that identifies the geographic location of your MongoDB cluster. The region you choose can affect network latency for clients accessing your databases. For multi-region clusters, see **replicationSpec.{region}**.
	RegionName *string `json:"regionName,omitempty"`
}

// NewApiAtlasAzureProviderSettingsViewManualAllOf instantiates a new ApiAtlasAzureProviderSettingsViewManualAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasAzureProviderSettingsViewManualAllOf() *ApiAtlasAzureProviderSettingsViewManualAllOf {
	this := ApiAtlasAzureProviderSettingsViewManualAllOf{}
	return &this
}

// NewApiAtlasAzureProviderSettingsViewManualAllOfWithDefaults instantiates a new ApiAtlasAzureProviderSettingsViewManualAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasAzureProviderSettingsViewManualAllOfWithDefaults() *ApiAtlasAzureProviderSettingsViewManualAllOf {
	this := ApiAtlasAzureProviderSettingsViewManualAllOf{}
	return &this
}

// GetAutoScaling returns the AutoScaling field value if set, zero value otherwise.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) GetAutoScaling() ApiAtlasAzureProviderSettingsViewManualAllOfAutoScaling {
	if o == nil || isNil(o.AutoScaling) {
		var ret ApiAtlasAzureProviderSettingsViewManualAllOfAutoScaling
		return ret
	}
	return *o.AutoScaling
}

// GetAutoScalingOk returns a tuple with the AutoScaling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) GetAutoScalingOk() (*ApiAtlasAzureProviderSettingsViewManualAllOfAutoScaling, bool) {
	if o == nil || isNil(o.AutoScaling) {
    return nil, false
	}
	return o.AutoScaling, true
}

// HasAutoScaling returns a boolean if a field has been set.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) HasAutoScaling() bool {
	if o != nil && !isNil(o.AutoScaling) {
		return true
	}

	return false
}

// SetAutoScaling gets a reference to the given ApiAtlasAzureProviderSettingsViewManualAllOfAutoScaling and assigns it to the AutoScaling field.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) SetAutoScaling(v ApiAtlasAzureProviderSettingsViewManualAllOfAutoScaling) {
	o.AutoScaling = &v
}

// GetDiskTypeName returns the DiskTypeName field value if set, zero value otherwise.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) GetDiskTypeName() string {
	if o == nil || isNil(o.DiskTypeName) {
		var ret string
		return ret
	}
	return *o.DiskTypeName
}

// GetDiskTypeNameOk returns a tuple with the DiskTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) GetDiskTypeNameOk() (*string, bool) {
	if o == nil || isNil(o.DiskTypeName) {
    return nil, false
	}
	return o.DiskTypeName, true
}

// HasDiskTypeName returns a boolean if a field has been set.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) HasDiskTypeName() bool {
	if o != nil && !isNil(o.DiskTypeName) {
		return true
	}

	return false
}

// SetDiskTypeName gets a reference to the given string and assigns it to the DiskTypeName field.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) SetDiskTypeName(v string) {
	o.DiskTypeName = &v
}

// GetInstanceSizeName returns the InstanceSizeName field value if set, zero value otherwise.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) GetInstanceSizeName() string {
	if o == nil || isNil(o.InstanceSizeName) {
		var ret string
		return ret
	}
	return *o.InstanceSizeName
}

// GetInstanceSizeNameOk returns a tuple with the InstanceSizeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) GetInstanceSizeNameOk() (*string, bool) {
	if o == nil || isNil(o.InstanceSizeName) {
    return nil, false
	}
	return o.InstanceSizeName, true
}

// HasInstanceSizeName returns a boolean if a field has been set.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) HasInstanceSizeName() bool {
	if o != nil && !isNil(o.InstanceSizeName) {
		return true
	}

	return false
}

// SetInstanceSizeName gets a reference to the given string and assigns it to the InstanceSizeName field.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) SetInstanceSizeName(v string) {
	o.InstanceSizeName = &v
}

// GetRegionName returns the RegionName field value if set, zero value otherwise.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) GetRegionName() string {
	if o == nil || isNil(o.RegionName) {
		var ret string
		return ret
	}
	return *o.RegionName
}

// GetRegionNameOk returns a tuple with the RegionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) GetRegionNameOk() (*string, bool) {
	if o == nil || isNil(o.RegionName) {
    return nil, false
	}
	return o.RegionName, true
}

// HasRegionName returns a boolean if a field has been set.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) HasRegionName() bool {
	if o != nil && !isNil(o.RegionName) {
		return true
	}

	return false
}

// SetRegionName gets a reference to the given string and assigns it to the RegionName field.
func (o *ApiAtlasAzureProviderSettingsViewManualAllOf) SetRegionName(v string) {
	o.RegionName = &v
}

func (o ApiAtlasAzureProviderSettingsViewManualAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AutoScaling) {
		toSerialize["autoScaling"] = o.AutoScaling
	}
	if !isNil(o.DiskTypeName) {
		toSerialize["diskTypeName"] = o.DiskTypeName
	}
	if !isNil(o.InstanceSizeName) {
		toSerialize["instanceSizeName"] = o.InstanceSizeName
	}
	if !isNil(o.RegionName) {
		toSerialize["regionName"] = o.RegionName
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasAzureProviderSettingsViewManualAllOf struct {
	value *ApiAtlasAzureProviderSettingsViewManualAllOf
	isSet bool
}

func (v NullableApiAtlasAzureProviderSettingsViewManualAllOf) Get() *ApiAtlasAzureProviderSettingsViewManualAllOf {
	return v.value
}

func (v *NullableApiAtlasAzureProviderSettingsViewManualAllOf) Set(val *ApiAtlasAzureProviderSettingsViewManualAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasAzureProviderSettingsViewManualAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasAzureProviderSettingsViewManualAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasAzureProviderSettingsViewManualAllOf(val *ApiAtlasAzureProviderSettingsViewManualAllOf) *NullableApiAtlasAzureProviderSettingsViewManualAllOf {
	return &NullableApiAtlasAzureProviderSettingsViewManualAllOf{value: val, isSet: true}
}

func (v NullableApiAtlasAzureProviderSettingsViewManualAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasAzureProviderSettingsViewManualAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


