/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiAtlasDataLakeDatabaseDataSourceView Data store that maps to a collection for this data lake.
type ApiAtlasDataLakeDatabaseDataSourceView struct {
	// Flag that validates the scheme in the specified URLs. If `true`, allows insecure `HTTP` scheme, doesn't verify the server's certificate chain and hostname, and accepts any certificate with any hostname presented by the server. If `false`, allows secure `HTTPS` scheme only.
	AllowInsecure *bool `json:"allowInsecure,omitempty"`
	// Human-readable label that identifies the collection in the database. For creating a wildcard (`*`) collection, you must omit this parameter.
	Collection *string `json:"collection,omitempty"`
	// Regex pattern to use for creating the wildcard (*) collection. To learn more about the regex syntax, see [Go programming language](https://pkg.go.dev/regexp).
	CollectionRegex *string `json:"collectionRegex,omitempty"`
	// Human-readable label that identifies the database, which contains the collection in the cluster. You must omit this parameter to generate wildcard (`*`) collections for dynamically generated databases.
	Database *string `json:"database,omitempty"`
	// File format that MongoDB Cloud uses if it encounters a file without a file extension while searching **storeName**.
	DefaultFormat *string `json:"defaultFormat,omitempty"`
	// File path that controls how MongoDB Cloud searches for and parses files in the **storeName** before mapping them to a collection.Specify ``/`` to capture all files and folders from the ``prefix`` path.
	Path *string `json:"path,omitempty"`
	// Human-readable label that identifies the data store that MongoDB Cloud maps to the collection.
	StoreName *string `json:"storeName,omitempty"`
	// URLs of the publicly accessible data files. You can't specify URLs that require authentication. Atlas Data Lake creates a partition for each URL. If empty or omitted, Data Lake uses the URLs from the store specified in the **dataSources.storeName** parameter.
	Urls []string `json:"urls,omitempty"`
}

// NewApiAtlasDataLakeDatabaseDataSourceView instantiates a new ApiAtlasDataLakeDatabaseDataSourceView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasDataLakeDatabaseDataSourceView() *ApiAtlasDataLakeDatabaseDataSourceView {
	this := ApiAtlasDataLakeDatabaseDataSourceView{}
	var allowInsecure bool = false
	this.AllowInsecure = &allowInsecure
	return &this
}

// NewApiAtlasDataLakeDatabaseDataSourceViewWithDefaults instantiates a new ApiAtlasDataLakeDatabaseDataSourceView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasDataLakeDatabaseDataSourceViewWithDefaults() *ApiAtlasDataLakeDatabaseDataSourceView {
	this := ApiAtlasDataLakeDatabaseDataSourceView{}
	var allowInsecure bool = false
	this.AllowInsecure = &allowInsecure
	return &this
}

// GetAllowInsecure returns the AllowInsecure field value if set, zero value otherwise.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetAllowInsecure() bool {
	if o == nil || isNil(o.AllowInsecure) {
		var ret bool
		return ret
	}
	return *o.AllowInsecure
}

// GetAllowInsecureOk returns a tuple with the AllowInsecure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetAllowInsecureOk() (*bool, bool) {
	if o == nil || isNil(o.AllowInsecure) {
    return nil, false
	}
	return o.AllowInsecure, true
}

// HasAllowInsecure returns a boolean if a field has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) HasAllowInsecure() bool {
	if o != nil && !isNil(o.AllowInsecure) {
		return true
	}

	return false
}

// SetAllowInsecure gets a reference to the given bool and assigns it to the AllowInsecure field.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) SetAllowInsecure(v bool) {
	o.AllowInsecure = &v
}

// GetCollection returns the Collection field value if set, zero value otherwise.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetCollection() string {
	if o == nil || isNil(o.Collection) {
		var ret string
		return ret
	}
	return *o.Collection
}

// GetCollectionOk returns a tuple with the Collection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetCollectionOk() (*string, bool) {
	if o == nil || isNil(o.Collection) {
    return nil, false
	}
	return o.Collection, true
}

// HasCollection returns a boolean if a field has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) HasCollection() bool {
	if o != nil && !isNil(o.Collection) {
		return true
	}

	return false
}

// SetCollection gets a reference to the given string and assigns it to the Collection field.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) SetCollection(v string) {
	o.Collection = &v
}

// GetCollectionRegex returns the CollectionRegex field value if set, zero value otherwise.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetCollectionRegex() string {
	if o == nil || isNil(o.CollectionRegex) {
		var ret string
		return ret
	}
	return *o.CollectionRegex
}

// GetCollectionRegexOk returns a tuple with the CollectionRegex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetCollectionRegexOk() (*string, bool) {
	if o == nil || isNil(o.CollectionRegex) {
    return nil, false
	}
	return o.CollectionRegex, true
}

// HasCollectionRegex returns a boolean if a field has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) HasCollectionRegex() bool {
	if o != nil && !isNil(o.CollectionRegex) {
		return true
	}

	return false
}

// SetCollectionRegex gets a reference to the given string and assigns it to the CollectionRegex field.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) SetCollectionRegex(v string) {
	o.CollectionRegex = &v
}

// GetDatabase returns the Database field value if set, zero value otherwise.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetDatabase() string {
	if o == nil || isNil(o.Database) {
		var ret string
		return ret
	}
	return *o.Database
}

// GetDatabaseOk returns a tuple with the Database field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetDatabaseOk() (*string, bool) {
	if o == nil || isNil(o.Database) {
    return nil, false
	}
	return o.Database, true
}

// HasDatabase returns a boolean if a field has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) HasDatabase() bool {
	if o != nil && !isNil(o.Database) {
		return true
	}

	return false
}

// SetDatabase gets a reference to the given string and assigns it to the Database field.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) SetDatabase(v string) {
	o.Database = &v
}

// GetDefaultFormat returns the DefaultFormat field value if set, zero value otherwise.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetDefaultFormat() string {
	if o == nil || isNil(o.DefaultFormat) {
		var ret string
		return ret
	}
	return *o.DefaultFormat
}

// GetDefaultFormatOk returns a tuple with the DefaultFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetDefaultFormatOk() (*string, bool) {
	if o == nil || isNil(o.DefaultFormat) {
    return nil, false
	}
	return o.DefaultFormat, true
}

// HasDefaultFormat returns a boolean if a field has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) HasDefaultFormat() bool {
	if o != nil && !isNil(o.DefaultFormat) {
		return true
	}

	return false
}

// SetDefaultFormat gets a reference to the given string and assigns it to the DefaultFormat field.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) SetDefaultFormat(v string) {
	o.DefaultFormat = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetPath() string {
	if o == nil || isNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetPathOk() (*string, bool) {
	if o == nil || isNil(o.Path) {
    return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) HasPath() bool {
	if o != nil && !isNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) SetPath(v string) {
	o.Path = &v
}

// GetStoreName returns the StoreName field value if set, zero value otherwise.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetStoreName() string {
	if o == nil || isNil(o.StoreName) {
		var ret string
		return ret
	}
	return *o.StoreName
}

// GetStoreNameOk returns a tuple with the StoreName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetStoreNameOk() (*string, bool) {
	if o == nil || isNil(o.StoreName) {
    return nil, false
	}
	return o.StoreName, true
}

// HasStoreName returns a boolean if a field has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) HasStoreName() bool {
	if o != nil && !isNil(o.StoreName) {
		return true
	}

	return false
}

// SetStoreName gets a reference to the given string and assigns it to the StoreName field.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) SetStoreName(v string) {
	o.StoreName = &v
}

// GetUrls returns the Urls field value if set, zero value otherwise.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetUrls() []string {
	if o == nil || isNil(o.Urls) {
		var ret []string
		return ret
	}
	return o.Urls
}

// GetUrlsOk returns a tuple with the Urls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) GetUrlsOk() ([]string, bool) {
	if o == nil || isNil(o.Urls) {
    return nil, false
	}
	return o.Urls, true
}

// HasUrls returns a boolean if a field has been set.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) HasUrls() bool {
	if o != nil && !isNil(o.Urls) {
		return true
	}

	return false
}

// SetUrls gets a reference to the given []string and assigns it to the Urls field.
func (o *ApiAtlasDataLakeDatabaseDataSourceView) SetUrls(v []string) {
	o.Urls = v
}

func (o ApiAtlasDataLakeDatabaseDataSourceView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AllowInsecure) {
		toSerialize["allowInsecure"] = o.AllowInsecure
	}
	if !isNil(o.Collection) {
		toSerialize["collection"] = o.Collection
	}
	if !isNil(o.CollectionRegex) {
		toSerialize["collectionRegex"] = o.CollectionRegex
	}
	if !isNil(o.Database) {
		toSerialize["database"] = o.Database
	}
	if !isNil(o.DefaultFormat) {
		toSerialize["defaultFormat"] = o.DefaultFormat
	}
	if !isNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !isNil(o.StoreName) {
		toSerialize["storeName"] = o.StoreName
	}
	if !isNil(o.Urls) {
		toSerialize["urls"] = o.Urls
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasDataLakeDatabaseDataSourceView struct {
	value *ApiAtlasDataLakeDatabaseDataSourceView
	isSet bool
}

func (v NullableApiAtlasDataLakeDatabaseDataSourceView) Get() *ApiAtlasDataLakeDatabaseDataSourceView {
	return v.value
}

func (v *NullableApiAtlasDataLakeDatabaseDataSourceView) Set(val *ApiAtlasDataLakeDatabaseDataSourceView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasDataLakeDatabaseDataSourceView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasDataLakeDatabaseDataSourceView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasDataLakeDatabaseDataSourceView(val *ApiAtlasDataLakeDatabaseDataSourceView) *NullableApiAtlasDataLakeDatabaseDataSourceView {
	return &NullableApiAtlasDataLakeDatabaseDataSourceView{value: val, isSet: true}
}

func (v NullableApiAtlasDataLakeDatabaseDataSourceView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasDataLakeDatabaseDataSourceView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


