/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiAtlasServerlessAzureTenantEndpointUpdateView Updates to a serverless Azure tenant endpoint.
type ApiAtlasServerlessAzureTenantEndpointUpdateView struct {
	// IPv4 address of the private endpoint in your Azure VNet that someone added to this private endpoint service.
	PrivateEndpointIpAddress *string `json:"privateEndpointIpAddress,omitempty"`
}

// NewApiAtlasServerlessAzureTenantEndpointUpdateView instantiates a new ApiAtlasServerlessAzureTenantEndpointUpdateView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasServerlessAzureTenantEndpointUpdateView(providerName string) *ApiAtlasServerlessAzureTenantEndpointUpdateView {
	this := ApiAtlasServerlessAzureTenantEndpointUpdateView{}
	this.ProviderName = providerName
	return &this
}

// NewApiAtlasServerlessAzureTenantEndpointUpdateViewWithDefaults instantiates a new ApiAtlasServerlessAzureTenantEndpointUpdateView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasServerlessAzureTenantEndpointUpdateViewWithDefaults() *ApiAtlasServerlessAzureTenantEndpointUpdateView {
	this := ApiAtlasServerlessAzureTenantEndpointUpdateView{}
	return &this
}

// GetPrivateEndpointIpAddress returns the PrivateEndpointIpAddress field value if set, zero value otherwise.
func (o *ApiAtlasServerlessAzureTenantEndpointUpdateView) GetPrivateEndpointIpAddress() string {
	if o == nil || isNil(o.PrivateEndpointIpAddress) {
		var ret string
		return ret
	}
	return *o.PrivateEndpointIpAddress
}

// GetPrivateEndpointIpAddressOk returns a tuple with the PrivateEndpointIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasServerlessAzureTenantEndpointUpdateView) GetPrivateEndpointIpAddressOk() (*string, bool) {
	if o == nil || isNil(o.PrivateEndpointIpAddress) {
    return nil, false
	}
	return o.PrivateEndpointIpAddress, true
}

// HasPrivateEndpointIpAddress returns a boolean if a field has been set.
func (o *ApiAtlasServerlessAzureTenantEndpointUpdateView) HasPrivateEndpointIpAddress() bool {
	if o != nil && !isNil(o.PrivateEndpointIpAddress) {
		return true
	}

	return false
}

// SetPrivateEndpointIpAddress gets a reference to the given string and assigns it to the PrivateEndpointIpAddress field.
func (o *ApiAtlasServerlessAzureTenantEndpointUpdateView) SetPrivateEndpointIpAddress(v string) {
	o.PrivateEndpointIpAddress = &v
}

func (o ApiAtlasServerlessAzureTenantEndpointUpdateView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PrivateEndpointIpAddress) {
		toSerialize["privateEndpointIpAddress"] = o.PrivateEndpointIpAddress
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasServerlessAzureTenantEndpointUpdateView struct {
	value *ApiAtlasServerlessAzureTenantEndpointUpdateView
	isSet bool
}

func (v NullableApiAtlasServerlessAzureTenantEndpointUpdateView) Get() *ApiAtlasServerlessAzureTenantEndpointUpdateView {
	return v.value
}

func (v *NullableApiAtlasServerlessAzureTenantEndpointUpdateView) Set(val *ApiAtlasServerlessAzureTenantEndpointUpdateView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasServerlessAzureTenantEndpointUpdateView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasServerlessAzureTenantEndpointUpdateView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasServerlessAzureTenantEndpointUpdateView(val *ApiAtlasServerlessAzureTenantEndpointUpdateView) *NullableApiAtlasServerlessAzureTenantEndpointUpdateView {
	return &NullableApiAtlasServerlessAzureTenantEndpointUpdateView{value: val, isSet: true}
}

func (v NullableApiAtlasServerlessAzureTenantEndpointUpdateView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasServerlessAzureTenantEndpointUpdateView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


