/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// ApiAtlasLegacyClusterDescriptionView struct for ApiAtlasLegacyClusterDescriptionView
type ApiAtlasLegacyClusterDescriptionView struct {
	AutoScaling *ApiAtlasAutoScalingView `json:"autoScaling,omitempty"`
	// Flag that indicates whether the cluster can perform backups. If set to `true`, the cluster can perform backups. You must set this value to `true` for NVMe clusters. Backup uses Cloud Backups for dedicated clusters and Shared Cluster Backups for tenant clusters. If set to `false`, the cluster doesn't use MongoDB Cloud backups.
	BackupEnabled *bool `json:"backupEnabled,omitempty"`
	BiConnector *ApiAtlasBiConnectorView `json:"biConnector,omitempty"`
	// Configuration of nodes that comprise the cluster.
	ClusterType *string `json:"clusterType,omitempty"`
	ConnectionStrings *ApiAtlasClusterDescriptionConnectionStringsView `json:"connectionStrings,omitempty"`
	// Date and time when MongoDB Cloud created this cluster. MongoDB Cloud represents this timestamp in ISO 8601 format in UTC.
	CreateDate *time.Time `json:"createDate,omitempty"`
	// Storage capacity that the host's root volume possesses expressed in gigabytes. Increase this number to add capacity. MongoDB Cloud requires this parameter if you set **replicationSpecs**. If you specify a disk size below the minimum (10 GB), this parameter defaults to the minimum disk size value. Storage charge calculations depend on whether you choose the default value or a custom value.  The maximum value for disk storage cannot exceed 50 times the maximum RAM for the selected cluster. If you require more storage space, consider upgrading your cluster to a higher tier.
	DiskSizeGB *float32 `json:"diskSizeGB,omitempty"`
	// Cloud service provider that manages your customer keys to provide an additional layer of Encryption at Rest for the cluster.
	EncryptionAtRestProvider *string `json:"encryptionAtRestProvider,omitempty"`
	// Unique 24-hexadecimal character string that identifies the project.
	GroupId *string `json:"groupId,omitempty"`
	// Unique 24-hexadecimal digit string that identifies the cluster.
	Id *string `json:"id,omitempty"`
	// Collection of key-value pairs between 1 to 255 characters in length that tag and categorize the cluster. The MongoDB Cloud console doesn't display your labels.
	Labels []ApiAtlasNDSLabelView `json:"labels,omitempty"`
	// List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
	Links []Link `json:"links"`
	// Major MongoDB version of the cluster. MongoDB Cloud deploys the cluster with the latest stable release of the specified version.
	MongoDBMajorVersion *string `json:"mongoDBMajorVersion,omitempty"`
	// Version of MongoDB that the cluster runs.
	MongoDBVersion *string `json:"mongoDBVersion,omitempty"`
	// Base connection string that you can use to connect to the cluster. MongoDB Cloud displays the string only after the cluster starts, not while it builds the cluster.
	MongoURI *string `json:"mongoURI,omitempty"`
	// Date and time when someone last updated the connection string. MongoDB Cloud represents this timestamp in ISO 8601 format in UTC.
	MongoURIUpdated *time.Time `json:"mongoURIUpdated,omitempty"`
	// Connection string that you can use to connect to the cluster including the `replicaSet`, `ssl`, and `authSource` query parameters with values appropriate for the cluster. You may need to add MongoDB database users. The response returns this parameter once the cluster can receive requests, not while it builds the cluster.
	MongoURIWithOptions *string `json:"mongoURIWithOptions,omitempty"`
	// Human-readable label that identifies the cluster.
	Name *string `json:"name,omitempty"`
	// Number of shards up to 50 to deploy for a sharded cluster. The resource returns `1` to indicate a replica set and values of `2` and higher to indicate a sharded cluster. The returned value equals the number of shards in the cluster.
	NumShards *int32 `json:"numShards,omitempty"`
	// Flag that indicates whether the cluster is paused.
	Paused *bool `json:"paused,omitempty"`
	// Flag that indicates whether the cluster uses continuous cloud backups.
	PitEnabled *bool `json:"pitEnabled,omitempty"`
	// Flag that indicates whether the M10 or higher cluster can perform Cloud Backups. If set to `true`, the cluster can perform backups. If this and **backupEnabled** are set to `false`, the cluster doesn't use MongoDB Cloud backups.
	ProviderBackupEnabled *bool `json:"providerBackupEnabled,omitempty"`
	ProviderSettings *ApiAtlasProviderSettingsViewManual `json:"providerSettings,omitempty"`
	// Number of members that belong to the replica set. Each member retains a copy of your databases, providing high availability and data redundancy. Use **replicationSpecs** instead.
	// Deprecated
	ReplicationFactor *int32 `json:"replicationFactor,omitempty"`
	// Physical location where MongoDB Cloud provisions cluster nodes.
	// Deprecated
	ReplicationSpec *map[string]ApiAtlasRegionSpecView `json:"replicationSpec,omitempty"`
	// List of settings that configure your cluster regions.  - For Global Clusters, each object in the array represents one zone where MongoDB Cloud deploys your clusters nodes. - For non-Global sharded clusters and replica sets, the single object represents where MongoDB Cloud deploys your clusters nodes.
	ReplicationSpecs []ApiAtlasLegacyReplicationSpecViewManual `json:"replicationSpecs,omitempty"`
	// Root Certificate Authority that MongoDB Atlas clusters uses. MongoDB Cloud supports Internet Security Research Group.
	RootCertType *string `json:"rootCertType,omitempty"`
	// Connection string that you can use to connect to the cluster. The `+srv` modifier forces the connection to use Transport Layer Security (TLS). The `mongoURI` parameter lists additional options.
	SrvAddress *string `json:"srvAddress,omitempty"`
	// Human-readable label that indicates the current operating condition of the cluster.
	StateName *string `json:"stateName,omitempty"`
	// Flag that indicates whether termination protection is enabled on the cluster. If set to `true`, MongoDB Cloud won't delete the cluster. If set to `false`, MongoDB Cloud will delete the cluster.
	TerminationProtectionEnabled *bool `json:"terminationProtectionEnabled,omitempty"`
	// Method by which the cluster maintains the MongoDB versions. If value is `CONTINUOUS`, you must not specify **mongoDBMajorVersion**.
	VersionReleaseSystem *string `json:"versionReleaseSystem,omitempty"`
}

// NewApiAtlasLegacyClusterDescriptionView instantiates a new ApiAtlasLegacyClusterDescriptionView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasLegacyClusterDescriptionView(links []Link) *ApiAtlasLegacyClusterDescriptionView {
	this := ApiAtlasLegacyClusterDescriptionView{}
	this.Links = links
	var mongoDBMajorVersion string = "4.4"
	this.MongoDBMajorVersion = &mongoDBMajorVersion
	var numShards int32 = 1
	this.NumShards = &numShards
	var replicationFactor int32 = 3
	this.ReplicationFactor = &replicationFactor
	var rootCertType string = "ISRGROOTX1"
	this.RootCertType = &rootCertType
	var terminationProtectionEnabled bool = false
	this.TerminationProtectionEnabled = &terminationProtectionEnabled
	var versionReleaseSystem string = "LTS"
	this.VersionReleaseSystem = &versionReleaseSystem
	return &this
}

// NewApiAtlasLegacyClusterDescriptionViewWithDefaults instantiates a new ApiAtlasLegacyClusterDescriptionView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasLegacyClusterDescriptionViewWithDefaults() *ApiAtlasLegacyClusterDescriptionView {
	this := ApiAtlasLegacyClusterDescriptionView{}
	var mongoDBMajorVersion string = "4.4"
	this.MongoDBMajorVersion = &mongoDBMajorVersion
	var numShards int32 = 1
	this.NumShards = &numShards
	var replicationFactor int32 = 3
	this.ReplicationFactor = &replicationFactor
	var rootCertType string = "ISRGROOTX1"
	this.RootCertType = &rootCertType
	var terminationProtectionEnabled bool = false
	this.TerminationProtectionEnabled = &terminationProtectionEnabled
	var versionReleaseSystem string = "LTS"
	this.VersionReleaseSystem = &versionReleaseSystem
	return &this
}

// GetAutoScaling returns the AutoScaling field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetAutoScaling() ApiAtlasAutoScalingView {
	if o == nil || isNil(o.AutoScaling) {
		var ret ApiAtlasAutoScalingView
		return ret
	}
	return *o.AutoScaling
}

// GetAutoScalingOk returns a tuple with the AutoScaling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetAutoScalingOk() (*ApiAtlasAutoScalingView, bool) {
	if o == nil || isNil(o.AutoScaling) {
    return nil, false
	}
	return o.AutoScaling, true
}

// HasAutoScaling returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasAutoScaling() bool {
	if o != nil && !isNil(o.AutoScaling) {
		return true
	}

	return false
}

// SetAutoScaling gets a reference to the given ApiAtlasAutoScalingView and assigns it to the AutoScaling field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetAutoScaling(v ApiAtlasAutoScalingView) {
	o.AutoScaling = &v
}

// GetBackupEnabled returns the BackupEnabled field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetBackupEnabled() bool {
	if o == nil || isNil(o.BackupEnabled) {
		var ret bool
		return ret
	}
	return *o.BackupEnabled
}

// GetBackupEnabledOk returns a tuple with the BackupEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetBackupEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.BackupEnabled) {
    return nil, false
	}
	return o.BackupEnabled, true
}

// HasBackupEnabled returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasBackupEnabled() bool {
	if o != nil && !isNil(o.BackupEnabled) {
		return true
	}

	return false
}

// SetBackupEnabled gets a reference to the given bool and assigns it to the BackupEnabled field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetBackupEnabled(v bool) {
	o.BackupEnabled = &v
}

// GetBiConnector returns the BiConnector field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetBiConnector() ApiAtlasBiConnectorView {
	if o == nil || isNil(o.BiConnector) {
		var ret ApiAtlasBiConnectorView
		return ret
	}
	return *o.BiConnector
}

// GetBiConnectorOk returns a tuple with the BiConnector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetBiConnectorOk() (*ApiAtlasBiConnectorView, bool) {
	if o == nil || isNil(o.BiConnector) {
    return nil, false
	}
	return o.BiConnector, true
}

// HasBiConnector returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasBiConnector() bool {
	if o != nil && !isNil(o.BiConnector) {
		return true
	}

	return false
}

// SetBiConnector gets a reference to the given ApiAtlasBiConnectorView and assigns it to the BiConnector field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetBiConnector(v ApiAtlasBiConnectorView) {
	o.BiConnector = &v
}

// GetClusterType returns the ClusterType field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetClusterType() string {
	if o == nil || isNil(o.ClusterType) {
		var ret string
		return ret
	}
	return *o.ClusterType
}

// GetClusterTypeOk returns a tuple with the ClusterType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetClusterTypeOk() (*string, bool) {
	if o == nil || isNil(o.ClusterType) {
    return nil, false
	}
	return o.ClusterType, true
}

// HasClusterType returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasClusterType() bool {
	if o != nil && !isNil(o.ClusterType) {
		return true
	}

	return false
}

// SetClusterType gets a reference to the given string and assigns it to the ClusterType field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetClusterType(v string) {
	o.ClusterType = &v
}

// GetConnectionStrings returns the ConnectionStrings field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetConnectionStrings() ApiAtlasClusterDescriptionConnectionStringsView {
	if o == nil || isNil(o.ConnectionStrings) {
		var ret ApiAtlasClusterDescriptionConnectionStringsView
		return ret
	}
	return *o.ConnectionStrings
}

// GetConnectionStringsOk returns a tuple with the ConnectionStrings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetConnectionStringsOk() (*ApiAtlasClusterDescriptionConnectionStringsView, bool) {
	if o == nil || isNil(o.ConnectionStrings) {
    return nil, false
	}
	return o.ConnectionStrings, true
}

// HasConnectionStrings returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasConnectionStrings() bool {
	if o != nil && !isNil(o.ConnectionStrings) {
		return true
	}

	return false
}

// SetConnectionStrings gets a reference to the given ApiAtlasClusterDescriptionConnectionStringsView and assigns it to the ConnectionStrings field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetConnectionStrings(v ApiAtlasClusterDescriptionConnectionStringsView) {
	o.ConnectionStrings = &v
}

// GetCreateDate returns the CreateDate field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetCreateDate() time.Time {
	if o == nil || isNil(o.CreateDate) {
		var ret time.Time
		return ret
	}
	return *o.CreateDate
}

// GetCreateDateOk returns a tuple with the CreateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetCreateDateOk() (*time.Time, bool) {
	if o == nil || isNil(o.CreateDate) {
    return nil, false
	}
	return o.CreateDate, true
}

// HasCreateDate returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasCreateDate() bool {
	if o != nil && !isNil(o.CreateDate) {
		return true
	}

	return false
}

// SetCreateDate gets a reference to the given time.Time and assigns it to the CreateDate field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetCreateDate(v time.Time) {
	o.CreateDate = &v
}

// GetDiskSizeGB returns the DiskSizeGB field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetDiskSizeGB() float32 {
	if o == nil || isNil(o.DiskSizeGB) {
		var ret float32
		return ret
	}
	return *o.DiskSizeGB
}

// GetDiskSizeGBOk returns a tuple with the DiskSizeGB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetDiskSizeGBOk() (*float32, bool) {
	if o == nil || isNil(o.DiskSizeGB) {
    return nil, false
	}
	return o.DiskSizeGB, true
}

// HasDiskSizeGB returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasDiskSizeGB() bool {
	if o != nil && !isNil(o.DiskSizeGB) {
		return true
	}

	return false
}

// SetDiskSizeGB gets a reference to the given float32 and assigns it to the DiskSizeGB field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetDiskSizeGB(v float32) {
	o.DiskSizeGB = &v
}

// GetEncryptionAtRestProvider returns the EncryptionAtRestProvider field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetEncryptionAtRestProvider() string {
	if o == nil || isNil(o.EncryptionAtRestProvider) {
		var ret string
		return ret
	}
	return *o.EncryptionAtRestProvider
}

// GetEncryptionAtRestProviderOk returns a tuple with the EncryptionAtRestProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetEncryptionAtRestProviderOk() (*string, bool) {
	if o == nil || isNil(o.EncryptionAtRestProvider) {
    return nil, false
	}
	return o.EncryptionAtRestProvider, true
}

// HasEncryptionAtRestProvider returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasEncryptionAtRestProvider() bool {
	if o != nil && !isNil(o.EncryptionAtRestProvider) {
		return true
	}

	return false
}

// SetEncryptionAtRestProvider gets a reference to the given string and assigns it to the EncryptionAtRestProvider field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetEncryptionAtRestProvider(v string) {
	o.EncryptionAtRestProvider = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetGroupId() string {
	if o == nil || isNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetGroupIdOk() (*string, bool) {
	if o == nil || isNil(o.GroupId) {
    return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasGroupId() bool {
	if o != nil && !isNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetGroupId(v string) {
	o.GroupId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetId(v string) {
	o.Id = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetLabels() []ApiAtlasNDSLabelView {
	if o == nil || isNil(o.Labels) {
		var ret []ApiAtlasNDSLabelView
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetLabelsOk() ([]ApiAtlasNDSLabelView, bool) {
	if o == nil || isNil(o.Labels) {
    return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasLabels() bool {
	if o != nil && !isNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []ApiAtlasNDSLabelView and assigns it to the Labels field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetLabels(v []ApiAtlasNDSLabelView) {
	o.Labels = v
}

// GetLinks returns the Links field value
func (o *ApiAtlasLegacyClusterDescriptionView) GetLinks() []Link {
	if o == nil {
		var ret []Link
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetLinksOk() ([]Link, bool) {
	if o == nil {
    return nil, false
	}
	return o.Links, true
}

// SetLinks sets field value
func (o *ApiAtlasLegacyClusterDescriptionView) SetLinks(v []Link) {
	o.Links = v
}

// GetMongoDBMajorVersion returns the MongoDBMajorVersion field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoDBMajorVersion() string {
	if o == nil || isNil(o.MongoDBMajorVersion) {
		var ret string
		return ret
	}
	return *o.MongoDBMajorVersion
}

// GetMongoDBMajorVersionOk returns a tuple with the MongoDBMajorVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoDBMajorVersionOk() (*string, bool) {
	if o == nil || isNil(o.MongoDBMajorVersion) {
    return nil, false
	}
	return o.MongoDBMajorVersion, true
}

// HasMongoDBMajorVersion returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasMongoDBMajorVersion() bool {
	if o != nil && !isNil(o.MongoDBMajorVersion) {
		return true
	}

	return false
}

// SetMongoDBMajorVersion gets a reference to the given string and assigns it to the MongoDBMajorVersion field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetMongoDBMajorVersion(v string) {
	o.MongoDBMajorVersion = &v
}

// GetMongoDBVersion returns the MongoDBVersion field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoDBVersion() string {
	if o == nil || isNil(o.MongoDBVersion) {
		var ret string
		return ret
	}
	return *o.MongoDBVersion
}

// GetMongoDBVersionOk returns a tuple with the MongoDBVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoDBVersionOk() (*string, bool) {
	if o == nil || isNil(o.MongoDBVersion) {
    return nil, false
	}
	return o.MongoDBVersion, true
}

// HasMongoDBVersion returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasMongoDBVersion() bool {
	if o != nil && !isNil(o.MongoDBVersion) {
		return true
	}

	return false
}

// SetMongoDBVersion gets a reference to the given string and assigns it to the MongoDBVersion field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetMongoDBVersion(v string) {
	o.MongoDBVersion = &v
}

// GetMongoURI returns the MongoURI field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoURI() string {
	if o == nil || isNil(o.MongoURI) {
		var ret string
		return ret
	}
	return *o.MongoURI
}

// GetMongoURIOk returns a tuple with the MongoURI field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoURIOk() (*string, bool) {
	if o == nil || isNil(o.MongoURI) {
    return nil, false
	}
	return o.MongoURI, true
}

// HasMongoURI returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasMongoURI() bool {
	if o != nil && !isNil(o.MongoURI) {
		return true
	}

	return false
}

// SetMongoURI gets a reference to the given string and assigns it to the MongoURI field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetMongoURI(v string) {
	o.MongoURI = &v
}

// GetMongoURIUpdated returns the MongoURIUpdated field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoURIUpdated() time.Time {
	if o == nil || isNil(o.MongoURIUpdated) {
		var ret time.Time
		return ret
	}
	return *o.MongoURIUpdated
}

// GetMongoURIUpdatedOk returns a tuple with the MongoURIUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoURIUpdatedOk() (*time.Time, bool) {
	if o == nil || isNil(o.MongoURIUpdated) {
    return nil, false
	}
	return o.MongoURIUpdated, true
}

// HasMongoURIUpdated returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasMongoURIUpdated() bool {
	if o != nil && !isNil(o.MongoURIUpdated) {
		return true
	}

	return false
}

// SetMongoURIUpdated gets a reference to the given time.Time and assigns it to the MongoURIUpdated field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetMongoURIUpdated(v time.Time) {
	o.MongoURIUpdated = &v
}

// GetMongoURIWithOptions returns the MongoURIWithOptions field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoURIWithOptions() string {
	if o == nil || isNil(o.MongoURIWithOptions) {
		var ret string
		return ret
	}
	return *o.MongoURIWithOptions
}

// GetMongoURIWithOptionsOk returns a tuple with the MongoURIWithOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetMongoURIWithOptionsOk() (*string, bool) {
	if o == nil || isNil(o.MongoURIWithOptions) {
    return nil, false
	}
	return o.MongoURIWithOptions, true
}

// HasMongoURIWithOptions returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasMongoURIWithOptions() bool {
	if o != nil && !isNil(o.MongoURIWithOptions) {
		return true
	}

	return false
}

// SetMongoURIWithOptions gets a reference to the given string and assigns it to the MongoURIWithOptions field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetMongoURIWithOptions(v string) {
	o.MongoURIWithOptions = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetName(v string) {
	o.Name = &v
}

// GetNumShards returns the NumShards field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetNumShards() int32 {
	if o == nil || isNil(o.NumShards) {
		var ret int32
		return ret
	}
	return *o.NumShards
}

// GetNumShardsOk returns a tuple with the NumShards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetNumShardsOk() (*int32, bool) {
	if o == nil || isNil(o.NumShards) {
    return nil, false
	}
	return o.NumShards, true
}

// HasNumShards returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasNumShards() bool {
	if o != nil && !isNil(o.NumShards) {
		return true
	}

	return false
}

// SetNumShards gets a reference to the given int32 and assigns it to the NumShards field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetNumShards(v int32) {
	o.NumShards = &v
}

// GetPaused returns the Paused field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetPaused() bool {
	if o == nil || isNil(o.Paused) {
		var ret bool
		return ret
	}
	return *o.Paused
}

// GetPausedOk returns a tuple with the Paused field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetPausedOk() (*bool, bool) {
	if o == nil || isNil(o.Paused) {
    return nil, false
	}
	return o.Paused, true
}

// HasPaused returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasPaused() bool {
	if o != nil && !isNil(o.Paused) {
		return true
	}

	return false
}

// SetPaused gets a reference to the given bool and assigns it to the Paused field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetPaused(v bool) {
	o.Paused = &v
}

// GetPitEnabled returns the PitEnabled field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetPitEnabled() bool {
	if o == nil || isNil(o.PitEnabled) {
		var ret bool
		return ret
	}
	return *o.PitEnabled
}

// GetPitEnabledOk returns a tuple with the PitEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetPitEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.PitEnabled) {
    return nil, false
	}
	return o.PitEnabled, true
}

// HasPitEnabled returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasPitEnabled() bool {
	if o != nil && !isNil(o.PitEnabled) {
		return true
	}

	return false
}

// SetPitEnabled gets a reference to the given bool and assigns it to the PitEnabled field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetPitEnabled(v bool) {
	o.PitEnabled = &v
}

// GetProviderBackupEnabled returns the ProviderBackupEnabled field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetProviderBackupEnabled() bool {
	if o == nil || isNil(o.ProviderBackupEnabled) {
		var ret bool
		return ret
	}
	return *o.ProviderBackupEnabled
}

// GetProviderBackupEnabledOk returns a tuple with the ProviderBackupEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetProviderBackupEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.ProviderBackupEnabled) {
    return nil, false
	}
	return o.ProviderBackupEnabled, true
}

// HasProviderBackupEnabled returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasProviderBackupEnabled() bool {
	if o != nil && !isNil(o.ProviderBackupEnabled) {
		return true
	}

	return false
}

// SetProviderBackupEnabled gets a reference to the given bool and assigns it to the ProviderBackupEnabled field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetProviderBackupEnabled(v bool) {
	o.ProviderBackupEnabled = &v
}

// GetProviderSettings returns the ProviderSettings field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetProviderSettings() ApiAtlasProviderSettingsViewManual {
	if o == nil || isNil(o.ProviderSettings) {
		var ret ApiAtlasProviderSettingsViewManual
		return ret
	}
	return *o.ProviderSettings
}

// GetProviderSettingsOk returns a tuple with the ProviderSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetProviderSettingsOk() (*ApiAtlasProviderSettingsViewManual, bool) {
	if o == nil || isNil(o.ProviderSettings) {
    return nil, false
	}
	return o.ProviderSettings, true
}

// HasProviderSettings returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasProviderSettings() bool {
	if o != nil && !isNil(o.ProviderSettings) {
		return true
	}

	return false
}

// SetProviderSettings gets a reference to the given ApiAtlasProviderSettingsViewManual and assigns it to the ProviderSettings field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetProviderSettings(v ApiAtlasProviderSettingsViewManual) {
	o.ProviderSettings = &v
}

// GetReplicationFactor returns the ReplicationFactor field value if set, zero value otherwise.
// Deprecated
func (o *ApiAtlasLegacyClusterDescriptionView) GetReplicationFactor() int32 {
	if o == nil || isNil(o.ReplicationFactor) {
		var ret int32
		return ret
	}
	return *o.ReplicationFactor
}

// GetReplicationFactorOk returns a tuple with the ReplicationFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *ApiAtlasLegacyClusterDescriptionView) GetReplicationFactorOk() (*int32, bool) {
	if o == nil || isNil(o.ReplicationFactor) {
    return nil, false
	}
	return o.ReplicationFactor, true
}

// HasReplicationFactor returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasReplicationFactor() bool {
	if o != nil && !isNil(o.ReplicationFactor) {
		return true
	}

	return false
}

// SetReplicationFactor gets a reference to the given int32 and assigns it to the ReplicationFactor field.
// Deprecated
func (o *ApiAtlasLegacyClusterDescriptionView) SetReplicationFactor(v int32) {
	o.ReplicationFactor = &v
}

// GetReplicationSpec returns the ReplicationSpec field value if set, zero value otherwise.
// Deprecated
func (o *ApiAtlasLegacyClusterDescriptionView) GetReplicationSpec() map[string]ApiAtlasRegionSpecView {
	if o == nil || isNil(o.ReplicationSpec) {
		var ret map[string]ApiAtlasRegionSpecView
		return ret
	}
	return *o.ReplicationSpec
}

// GetReplicationSpecOk returns a tuple with the ReplicationSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *ApiAtlasLegacyClusterDescriptionView) GetReplicationSpecOk() (*map[string]ApiAtlasRegionSpecView, bool) {
	if o == nil || isNil(o.ReplicationSpec) {
    return nil, false
	}
	return o.ReplicationSpec, true
}

// HasReplicationSpec returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasReplicationSpec() bool {
	if o != nil && !isNil(o.ReplicationSpec) {
		return true
	}

	return false
}

// SetReplicationSpec gets a reference to the given map[string]ApiAtlasRegionSpecView and assigns it to the ReplicationSpec field.
// Deprecated
func (o *ApiAtlasLegacyClusterDescriptionView) SetReplicationSpec(v map[string]ApiAtlasRegionSpecView) {
	o.ReplicationSpec = &v
}

// GetReplicationSpecs returns the ReplicationSpecs field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetReplicationSpecs() []ApiAtlasLegacyReplicationSpecViewManual {
	if o == nil || isNil(o.ReplicationSpecs) {
		var ret []ApiAtlasLegacyReplicationSpecViewManual
		return ret
	}
	return o.ReplicationSpecs
}

// GetReplicationSpecsOk returns a tuple with the ReplicationSpecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetReplicationSpecsOk() ([]ApiAtlasLegacyReplicationSpecViewManual, bool) {
	if o == nil || isNil(o.ReplicationSpecs) {
    return nil, false
	}
	return o.ReplicationSpecs, true
}

// HasReplicationSpecs returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasReplicationSpecs() bool {
	if o != nil && !isNil(o.ReplicationSpecs) {
		return true
	}

	return false
}

// SetReplicationSpecs gets a reference to the given []ApiAtlasLegacyReplicationSpecViewManual and assigns it to the ReplicationSpecs field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetReplicationSpecs(v []ApiAtlasLegacyReplicationSpecViewManual) {
	o.ReplicationSpecs = v
}

// GetRootCertType returns the RootCertType field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetRootCertType() string {
	if o == nil || isNil(o.RootCertType) {
		var ret string
		return ret
	}
	return *o.RootCertType
}

// GetRootCertTypeOk returns a tuple with the RootCertType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetRootCertTypeOk() (*string, bool) {
	if o == nil || isNil(o.RootCertType) {
    return nil, false
	}
	return o.RootCertType, true
}

// HasRootCertType returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasRootCertType() bool {
	if o != nil && !isNil(o.RootCertType) {
		return true
	}

	return false
}

// SetRootCertType gets a reference to the given string and assigns it to the RootCertType field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetRootCertType(v string) {
	o.RootCertType = &v
}

// GetSrvAddress returns the SrvAddress field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetSrvAddress() string {
	if o == nil || isNil(o.SrvAddress) {
		var ret string
		return ret
	}
	return *o.SrvAddress
}

// GetSrvAddressOk returns a tuple with the SrvAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetSrvAddressOk() (*string, bool) {
	if o == nil || isNil(o.SrvAddress) {
    return nil, false
	}
	return o.SrvAddress, true
}

// HasSrvAddress returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasSrvAddress() bool {
	if o != nil && !isNil(o.SrvAddress) {
		return true
	}

	return false
}

// SetSrvAddress gets a reference to the given string and assigns it to the SrvAddress field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetSrvAddress(v string) {
	o.SrvAddress = &v
}

// GetStateName returns the StateName field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetStateName() string {
	if o == nil || isNil(o.StateName) {
		var ret string
		return ret
	}
	return *o.StateName
}

// GetStateNameOk returns a tuple with the StateName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetStateNameOk() (*string, bool) {
	if o == nil || isNil(o.StateName) {
    return nil, false
	}
	return o.StateName, true
}

// HasStateName returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasStateName() bool {
	if o != nil && !isNil(o.StateName) {
		return true
	}

	return false
}

// SetStateName gets a reference to the given string and assigns it to the StateName field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetStateName(v string) {
	o.StateName = &v
}

// GetTerminationProtectionEnabled returns the TerminationProtectionEnabled field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetTerminationProtectionEnabled() bool {
	if o == nil || isNil(o.TerminationProtectionEnabled) {
		var ret bool
		return ret
	}
	return *o.TerminationProtectionEnabled
}

// GetTerminationProtectionEnabledOk returns a tuple with the TerminationProtectionEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetTerminationProtectionEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.TerminationProtectionEnabled) {
    return nil, false
	}
	return o.TerminationProtectionEnabled, true
}

// HasTerminationProtectionEnabled returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasTerminationProtectionEnabled() bool {
	if o != nil && !isNil(o.TerminationProtectionEnabled) {
		return true
	}

	return false
}

// SetTerminationProtectionEnabled gets a reference to the given bool and assigns it to the TerminationProtectionEnabled field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetTerminationProtectionEnabled(v bool) {
	o.TerminationProtectionEnabled = &v
}

// GetVersionReleaseSystem returns the VersionReleaseSystem field value if set, zero value otherwise.
func (o *ApiAtlasLegacyClusterDescriptionView) GetVersionReleaseSystem() string {
	if o == nil || isNil(o.VersionReleaseSystem) {
		var ret string
		return ret
	}
	return *o.VersionReleaseSystem
}

// GetVersionReleaseSystemOk returns a tuple with the VersionReleaseSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) GetVersionReleaseSystemOk() (*string, bool) {
	if o == nil || isNil(o.VersionReleaseSystem) {
    return nil, false
	}
	return o.VersionReleaseSystem, true
}

// HasVersionReleaseSystem returns a boolean if a field has been set.
func (o *ApiAtlasLegacyClusterDescriptionView) HasVersionReleaseSystem() bool {
	if o != nil && !isNil(o.VersionReleaseSystem) {
		return true
	}

	return false
}

// SetVersionReleaseSystem gets a reference to the given string and assigns it to the VersionReleaseSystem field.
func (o *ApiAtlasLegacyClusterDescriptionView) SetVersionReleaseSystem(v string) {
	o.VersionReleaseSystem = &v
}

func (o ApiAtlasLegacyClusterDescriptionView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AutoScaling) {
		toSerialize["autoScaling"] = o.AutoScaling
	}
	if !isNil(o.BackupEnabled) {
		toSerialize["backupEnabled"] = o.BackupEnabled
	}
	if !isNil(o.BiConnector) {
		toSerialize["biConnector"] = o.BiConnector
	}
	if !isNil(o.ClusterType) {
		toSerialize["clusterType"] = o.ClusterType
	}
	if !isNil(o.ConnectionStrings) {
		toSerialize["connectionStrings"] = o.ConnectionStrings
	}
	if !isNil(o.CreateDate) {
		toSerialize["createDate"] = o.CreateDate
	}
	if !isNil(o.DiskSizeGB) {
		toSerialize["diskSizeGB"] = o.DiskSizeGB
	}
	if !isNil(o.EncryptionAtRestProvider) {
		toSerialize["encryptionAtRestProvider"] = o.EncryptionAtRestProvider
	}
	if !isNil(o.GroupId) {
		toSerialize["groupId"] = o.GroupId
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if true {
		toSerialize["links"] = o.Links
	}
	if !isNil(o.MongoDBMajorVersion) {
		toSerialize["mongoDBMajorVersion"] = o.MongoDBMajorVersion
	}
	if !isNil(o.MongoDBVersion) {
		toSerialize["mongoDBVersion"] = o.MongoDBVersion
	}
	if !isNil(o.MongoURI) {
		toSerialize["mongoURI"] = o.MongoURI
	}
	if !isNil(o.MongoURIUpdated) {
		toSerialize["mongoURIUpdated"] = o.MongoURIUpdated
	}
	if !isNil(o.MongoURIWithOptions) {
		toSerialize["mongoURIWithOptions"] = o.MongoURIWithOptions
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.NumShards) {
		toSerialize["numShards"] = o.NumShards
	}
	if !isNil(o.Paused) {
		toSerialize["paused"] = o.Paused
	}
	if !isNil(o.PitEnabled) {
		toSerialize["pitEnabled"] = o.PitEnabled
	}
	if !isNil(o.ProviderBackupEnabled) {
		toSerialize["providerBackupEnabled"] = o.ProviderBackupEnabled
	}
	if !isNil(o.ProviderSettings) {
		toSerialize["providerSettings"] = o.ProviderSettings
	}
	if !isNil(o.ReplicationFactor) {
		toSerialize["replicationFactor"] = o.ReplicationFactor
	}
	if !isNil(o.ReplicationSpec) {
		toSerialize["replicationSpec"] = o.ReplicationSpec
	}
	if !isNil(o.ReplicationSpecs) {
		toSerialize["replicationSpecs"] = o.ReplicationSpecs
	}
	if !isNil(o.RootCertType) {
		toSerialize["rootCertType"] = o.RootCertType
	}
	if !isNil(o.SrvAddress) {
		toSerialize["srvAddress"] = o.SrvAddress
	}
	if !isNil(o.StateName) {
		toSerialize["stateName"] = o.StateName
	}
	if !isNil(o.TerminationProtectionEnabled) {
		toSerialize["terminationProtectionEnabled"] = o.TerminationProtectionEnabled
	}
	if !isNil(o.VersionReleaseSystem) {
		toSerialize["versionReleaseSystem"] = o.VersionReleaseSystem
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasLegacyClusterDescriptionView struct {
	value *ApiAtlasLegacyClusterDescriptionView
	isSet bool
}

func (v NullableApiAtlasLegacyClusterDescriptionView) Get() *ApiAtlasLegacyClusterDescriptionView {
	return v.value
}

func (v *NullableApiAtlasLegacyClusterDescriptionView) Set(val *ApiAtlasLegacyClusterDescriptionView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasLegacyClusterDescriptionView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasLegacyClusterDescriptionView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasLegacyClusterDescriptionView(val *ApiAtlasLegacyClusterDescriptionView) *NullableApiAtlasLegacyClusterDescriptionView {
	return &NullableApiAtlasLegacyClusterDescriptionView{value: val, isSet: true}
}

func (v NullableApiAtlasLegacyClusterDescriptionView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasLegacyClusterDescriptionView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


