/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiWebhookView Details to integrate one webhook with one MongoDB Cloud project.
type ApiWebhookView struct {
	// Parameter returned if someone configure this webhook with a secret.
	Secret *string `json:"secret,omitempty"`
	// Endpoint web address to which MongoDB Cloud sends notifications.
	Url string `json:"url"`
}

// NewApiWebhookView instantiates a new ApiWebhookView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiWebhookView(url string) *ApiWebhookView {
	this := ApiWebhookView{}
	this.Url = url
	return &this
}

// NewApiWebhookViewWithDefaults instantiates a new ApiWebhookView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiWebhookViewWithDefaults() *ApiWebhookView {
	this := ApiWebhookView{}
	return &this
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *ApiWebhookView) GetSecret() string {
	if o == nil || isNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiWebhookView) GetSecretOk() (*string, bool) {
	if o == nil || isNil(o.Secret) {
    return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *ApiWebhookView) HasSecret() bool {
	if o != nil && !isNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *ApiWebhookView) SetSecret(v string) {
	o.Secret = &v
}

// GetUrl returns the Url field value
func (o *ApiWebhookView) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ApiWebhookView) GetUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ApiWebhookView) SetUrl(v string) {
	o.Url = v
}

func (o ApiWebhookView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if true {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableApiWebhookView struct {
	value *ApiWebhookView
	isSet bool
}

func (v NullableApiWebhookView) Get() *ApiWebhookView {
	return v.value
}

func (v *NullableApiWebhookView) Set(val *ApiWebhookView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiWebhookView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiWebhookView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiWebhookView(val *ApiWebhookView) *NullableApiWebhookView {
	return &NullableApiWebhookView{value: val, isSet: true}
}

func (v NullableApiWebhookView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiWebhookView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


