/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiAtlasCloudProviderAccessFeatureUsageView MongoDB Cloud features associated with this Amazon Web Services (AWS) Identity and Access Management (IAM) role.
type ApiAtlasCloudProviderAccessFeatureUsageView struct {
	// Human-readable label that describes one MongoDB Cloud feature linked to this Amazon Web Services (AWS) Identity and Access Management (IAM) role.
	FeatureType *string `json:"featureType,omitempty"`
}

// NewApiAtlasCloudProviderAccessFeatureUsageView instantiates a new ApiAtlasCloudProviderAccessFeatureUsageView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasCloudProviderAccessFeatureUsageView() *ApiAtlasCloudProviderAccessFeatureUsageView {
	this := ApiAtlasCloudProviderAccessFeatureUsageView{}
	return &this
}

// NewApiAtlasCloudProviderAccessFeatureUsageViewWithDefaults instantiates a new ApiAtlasCloudProviderAccessFeatureUsageView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasCloudProviderAccessFeatureUsageViewWithDefaults() *ApiAtlasCloudProviderAccessFeatureUsageView {
	this := ApiAtlasCloudProviderAccessFeatureUsageView{}
	return &this
}

// GetFeatureType returns the FeatureType field value if set, zero value otherwise.
func (o *ApiAtlasCloudProviderAccessFeatureUsageView) GetFeatureType() string {
	if o == nil || isNil(o.FeatureType) {
		var ret string
		return ret
	}
	return *o.FeatureType
}

// GetFeatureTypeOk returns a tuple with the FeatureType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasCloudProviderAccessFeatureUsageView) GetFeatureTypeOk() (*string, bool) {
	if o == nil || isNil(o.FeatureType) {
    return nil, false
	}
	return o.FeatureType, true
}

// HasFeatureType returns a boolean if a field has been set.
func (o *ApiAtlasCloudProviderAccessFeatureUsageView) HasFeatureType() bool {
	if o != nil && !isNil(o.FeatureType) {
		return true
	}

	return false
}

// SetFeatureType gets a reference to the given string and assigns it to the FeatureType field.
func (o *ApiAtlasCloudProviderAccessFeatureUsageView) SetFeatureType(v string) {
	o.FeatureType = &v
}

func (o ApiAtlasCloudProviderAccessFeatureUsageView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.FeatureType) {
		toSerialize["featureType"] = o.FeatureType
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasCloudProviderAccessFeatureUsageView struct {
	value *ApiAtlasCloudProviderAccessFeatureUsageView
	isSet bool
}

func (v NullableApiAtlasCloudProviderAccessFeatureUsageView) Get() *ApiAtlasCloudProviderAccessFeatureUsageView {
	return v.value
}

func (v *NullableApiAtlasCloudProviderAccessFeatureUsageView) Set(val *ApiAtlasCloudProviderAccessFeatureUsageView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasCloudProviderAccessFeatureUsageView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasCloudProviderAccessFeatureUsageView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasCloudProviderAccessFeatureUsageView(val *ApiAtlasCloudProviderAccessFeatureUsageView) *NullableApiAtlasCloudProviderAccessFeatureUsageView {
	return &NullableApiAtlasCloudProviderAccessFeatureUsageView{value: val, isSet: true}
}

func (v NullableApiAtlasCloudProviderAccessFeatureUsageView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasCloudProviderAccessFeatureUsageView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


