/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiAtlasTriggerIngestionRequestView struct for ApiAtlasTriggerIngestionRequestView
type ApiAtlasTriggerIngestionRequestView struct {
	// Unique 24-hexadecimal character string that identifies the snapshot.
	SnapshotId string `json:"snapshotId"`
}

// NewApiAtlasTriggerIngestionRequestView instantiates a new ApiAtlasTriggerIngestionRequestView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasTriggerIngestionRequestView(snapshotId string) *ApiAtlasTriggerIngestionRequestView {
	this := ApiAtlasTriggerIngestionRequestView{}
	this.SnapshotId = snapshotId
	return &this
}

// NewApiAtlasTriggerIngestionRequestViewWithDefaults instantiates a new ApiAtlasTriggerIngestionRequestView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasTriggerIngestionRequestViewWithDefaults() *ApiAtlasTriggerIngestionRequestView {
	this := ApiAtlasTriggerIngestionRequestView{}
	return &this
}

// GetSnapshotId returns the SnapshotId field value
func (o *ApiAtlasTriggerIngestionRequestView) GetSnapshotId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SnapshotId
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value
// and a boolean to check if the value has been set.
func (o *ApiAtlasTriggerIngestionRequestView) GetSnapshotIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SnapshotId, true
}

// SetSnapshotId sets field value
func (o *ApiAtlasTriggerIngestionRequestView) SetSnapshotId(v string) {
	o.SnapshotId = v
}

func (o ApiAtlasTriggerIngestionRequestView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["snapshotId"] = o.SnapshotId
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasTriggerIngestionRequestView struct {
	value *ApiAtlasTriggerIngestionRequestView
	isSet bool
}

func (v NullableApiAtlasTriggerIngestionRequestView) Get() *ApiAtlasTriggerIngestionRequestView {
	return v.value
}

func (v *NullableApiAtlasTriggerIngestionRequestView) Set(val *ApiAtlasTriggerIngestionRequestView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasTriggerIngestionRequestView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasTriggerIngestionRequestView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasTriggerIngestionRequestView(val *ApiAtlasTriggerIngestionRequestView) *NullableApiAtlasTriggerIngestionRequestView {
	return &NullableApiAtlasTriggerIngestionRequestView{value: val, isSet: true}
}

func (v NullableApiAtlasTriggerIngestionRequestView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasTriggerIngestionRequestView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


