/*
MongoDB Atlas Administration API

The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiAtlasClusterOutageSimulationOutageFilterView struct for ApiAtlasClusterOutageSimulationOutageFilterView
type ApiAtlasClusterOutageSimulationOutageFilterView struct {
	// The cloud provider of the region that undergoes the outage simulation.
	CloudProvider *string `json:"cloudProvider,omitempty"`
	// The name of the region to undergo an outage simulation.
	RegionName *string `json:"regionName,omitempty"`
	// The type of cluster outage to simulate.  | Type       | Description | |------------|-------------| | `REGION`   | Simulates a cluster outage for a region.|
	Type *string `json:"type,omitempty"`
}

// NewApiAtlasClusterOutageSimulationOutageFilterView instantiates a new ApiAtlasClusterOutageSimulationOutageFilterView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAtlasClusterOutageSimulationOutageFilterView() *ApiAtlasClusterOutageSimulationOutageFilterView {
	this := ApiAtlasClusterOutageSimulationOutageFilterView{}
	return &this
}

// NewApiAtlasClusterOutageSimulationOutageFilterViewWithDefaults instantiates a new ApiAtlasClusterOutageSimulationOutageFilterView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAtlasClusterOutageSimulationOutageFilterViewWithDefaults() *ApiAtlasClusterOutageSimulationOutageFilterView {
	this := ApiAtlasClusterOutageSimulationOutageFilterView{}
	return &this
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) GetCloudProvider() string {
	if o == nil || isNil(o.CloudProvider) {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) GetCloudProviderOk() (*string, bool) {
	if o == nil || isNil(o.CloudProvider) {
    return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) HasCloudProvider() bool {
	if o != nil && !isNil(o.CloudProvider) {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetRegionName returns the RegionName field value if set, zero value otherwise.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) GetRegionName() string {
	if o == nil || isNil(o.RegionName) {
		var ret string
		return ret
	}
	return *o.RegionName
}

// GetRegionNameOk returns a tuple with the RegionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) GetRegionNameOk() (*string, bool) {
	if o == nil || isNil(o.RegionName) {
    return nil, false
	}
	return o.RegionName, true
}

// HasRegionName returns a boolean if a field has been set.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) HasRegionName() bool {
	if o != nil && !isNil(o.RegionName) {
		return true
	}

	return false
}

// SetRegionName gets a reference to the given string and assigns it to the RegionName field.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) SetRegionName(v string) {
	o.RegionName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
    return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiAtlasClusterOutageSimulationOutageFilterView) SetType(v string) {
	o.Type = &v
}

func (o ApiAtlasClusterOutageSimulationOutageFilterView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CloudProvider) {
		toSerialize["cloudProvider"] = o.CloudProvider
	}
	if !isNil(o.RegionName) {
		toSerialize["regionName"] = o.RegionName
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableApiAtlasClusterOutageSimulationOutageFilterView struct {
	value *ApiAtlasClusterOutageSimulationOutageFilterView
	isSet bool
}

func (v NullableApiAtlasClusterOutageSimulationOutageFilterView) Get() *ApiAtlasClusterOutageSimulationOutageFilterView {
	return v.value
}

func (v *NullableApiAtlasClusterOutageSimulationOutageFilterView) Set(val *ApiAtlasClusterOutageSimulationOutageFilterView) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAtlasClusterOutageSimulationOutageFilterView) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAtlasClusterOutageSimulationOutageFilterView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAtlasClusterOutageSimulationOutageFilterView(val *ApiAtlasClusterOutageSimulationOutageFilterView) *NullableApiAtlasClusterOutageSimulationOutageFilterView {
	return &NullableApiAtlasClusterOutageSimulationOutageFilterView{value: val, isSet: true}
}

func (v NullableApiAtlasClusterOutageSimulationOutageFilterView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAtlasClusterOutageSimulationOutageFilterView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


